In [1]:
# import dependencies
import json
import requests
import pandas as pd
from api_keys import census_api

In [3]:
# add 2011 crime data
homicide = pd.read_csv("Data/homicide.csv", encoding="utf-8") 
homicide.head()

,ID,CASE #,Date of Occurance,Primary Description,Description,Beat,District #,Year,Latitude,Longitude,District,Community Area,Updated On,Case #,Date of Occurrence,Case Number,Date,Primary Type
0,19976.0,HT405253,07/19/2011 04:00:00 PM,HOMICIDE,FIRST DEGREE MURDER,732,6.0,2011,41.766565,-87.638386,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20146.0,HT578691,11/07/2011 12:05:00 PM,HOMICIDE,FIRST DEGREE MURDER,2123,4.0,2011,41.822200,-87.602135,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20147.0,HT576092,11/05/2011 01:50:00 PM,HOMICIDE,FIRST DEGREE MURDER,1122,28.0,2011,41.877169,-87.719061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20148.0,HT581763,11/09/2011 02:00:00 PM,HOMICIDE,FIRST DEGREE MURDER,522,34.0,2011,41.688889,-87.628242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20149.0,HT582731,11/10/2011 02:40:00 AM,HOMICIDE,FIRST DEGREE MURDER,614,18.0,2011,41.741304,-87.659690,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN